routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\PostController;

/*
Route::get('', function () {
    return "hola admin";
});*/

Route::get('', [HomeController::class,'index'])->name('admin.home');

//la url empieza con 'categories', y las rutas empiezan con 'admin.categories'
Route::resource('categories',CategoryController::class)->names('admin.categories');
//min:11_16

//Crud de etiqetas
Route::resource('tags',TagController::class)->names('admin.tags');

Route::resource('posts',PostController::class)->names('admin.posts');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;

/*
Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/',[PostController::class,'index'])->name('posts.index');

Route::get('posts/{post}',[PostController::class,'show'])->name('posts.show');

Route::get('category/{category}',[PostController::class,'category'])->name('posts.category');

Route::get('tag/{tag}',[PostController::class,'tag'])->name('posts.tag');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/Admin/PostsIndex.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Post;
use Livewire\WithPagination;

class PostsIndex extends Component
{
    use WithPagination;
    protected $paginationTheme="bootstrap";
    public $search;
    public function updatingSearch(){
        $this->resetPage();
    }

    public function render()
    {
        $posts=Post::where('user_id',auth()->user()->id)
                ->where('name', 'LIKE','%' . $this->search . '%')
                ->latest('id')
                ->paginate();
        return view('livewire.admin.posts-index',compact('posts'));
    }
}

app/Http/Livewire/Navigation.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Category;

class Navigation extends Component
{
    public function render()
    {
        $categories=Category::all();
        return view('livewire.navigation',compact('categories'));
    }
}

resources/views/livewire/admin/posts-index.blade.php
<div class="card">
   
    <div class="card-header">
        <input wire:model="search" class="form-control" placeholder="Ingrese el nombre del post">
    </div>

    @if ($posts->count())
        
   
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($posts as $post)
                    <tr>
                        <td>{{$post->id}}</td>
                        <td>{{$post->name}}</td>
                        <td width="10px">
                            <a class="btn btn-primary btn-sm" href="{{route('admin.posts.edit',$post)}}">Editar</a>
                        </td>
                        <td width="10px">
                            <form action="{{route('admin.posts.destroy',$post)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit">Eliminar</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    </div>

    <div class="card-footer">
        {{$posts->links()}}
    </div>
    @else
    <div class="card-body">
    <strong>No hay ningún registro</strong>
    </div>
    @endif
</div>